# Generated by Django 4.2.7 on 2025-08-09 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meter_type', models.CharField(choices=[('hot', 'Hot Water'), ('cold', 'Cold Water')], max_length=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=0.005, help_text='Cost per liter', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_usage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('predicted_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='utilities.watermeter')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_reading', models.DecimalField(decimal_places=3, max_digits=10)),
                ('end_reading', models.DecimalField(decimal_places=3, max_digits=10)),
                ('usage_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=0.005, max_digits=8)),
                ('calculated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='utilities.watermeter')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('meter', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WaterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utilities.models.upload_water_image)),
                ('reading_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='utilities.watermeter')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('meter', 'timestamp')},
            },
        ),
    ]
